app/admin/views.py
# -*- coding: UTF-8 -*-
from flask import (Blueprint, render_template, request, flash, redirect,
                   url_for)
from werkzeug.security import check_password_hash, generate_password_hash
from RealProject import db
from app.auth.views.auth import login_required
from app.auth.models import User
from app.blog.models import Category, Post, Tag
from .forms import CategoryForm, PostForm, TagForm, CreateUserForm
import markdown

bp = Blueprint('admin',
               __name__,
               url_prefix='/admin',
               template_folder='templates',
               static_folder='static')


# 创建蓝图后，需在app里挂载
# 在RealProject/__init.py中注册
@bp.route('/')
# 装饰器 验证用户是否已登录
@login_required
# 模板路径追加admin，把名称相同的文件隔离开
def index():
    return render_template('admin/index.html')


""" 分类管理视图
category:      查看分类列表
category.add:  添加分类
category.edit: 编辑分类
category.del:  删除分类
"""


@bp.route('/category')
@login_required
def category():
    # 设置分页信息
    page = request.args.get('page', 1, type=int)
    pagination = Category.query.order_by(-Category.add_date).paginate(
        page, per_page=10, error_out=False)
    category_list = pagination.items

    # 可以通过for循环获取页码值
    # print([i for i in pagination.iter_pages()])

    # 获取分页数据
    # print(pagination.items)

    return render_template('admin/category.html',
                           category_list=category_list,
                           pagination=pagination)


# 分类添加视图
@bp.route('/category/add', methods=['GET', 'POST'])
@login_required
def category_add():
    # 引入表单form类后实例化
    form = CategoryForm()
    # 判断提交的是哪一种请求模式
    if form.validate_on_submit():
        # 数据通过验证后则执行下列语句
        category = Category(name=form.name.data, icon=form.icon.data)
        db.session.add(category)
        db.session.commit()
        flash(f'{form.name.data}分类添加成功')
        return redirect(url_for('admin.category'))
    return render_template('admin/category_form.html', form=form)


# 分类编辑视图 编辑哪一条要传入这一条的主键
@bp.route('/category/edit/<int:cate_id>', methods=['GET', 'POST'])
@login_required
# 编辑与添加可以公用表单 字段一致，编辑的核心是回显消息
def category_edit(cate_id):
    # 编辑博客分类
    cate = Category.query.get(cate_id)
    # 实例化表单 设置回显
    form = CategoryForm(name=cate.name, icon=cate.icon)

    if form.validate_on_submit():
        # 后台数据修改方法 重新赋值 form获取前端表单提交的值
        cate.name = form.name.data
        cate.icon = form.icon.data
        db.session.add(cate)
        db.session.commit()
        flash(f'{form.name.data}分类修改成功')
        return redirect(url_for('admin.category'))
    return render_template('admin/category_form.html', form=form)


# 分类删除视图
@bp.route('/category/delete/<int:cate_id>')
@login_required
# 编辑与添加可以公用表单 字段一致，编辑的核心是回显消息
def category_del(cate_id):
    cate = Category.query.get(cate_id)
    if cate:
        db.session.delete(cate)
        db.session.commit()
        flash(f'{cate.name}分类删除成功')
        return redirect(url_for('admin.category'))


""" 文章管理视图
article:      查看文章列表
article.add:  添加文章
article.edit: 编辑文章
article.del:  删除文章
"""


@bp.route('/article')
@login_required
def article():
    # 查看文章列表
    page = request.args.get('page', 1, type=int)
    # 对文章进行倒序排列并对其分页
    pagination = Post.query.order_by(-Post.add_date).paginate(page,
                                                              per_page=10,
                                                              error_out=False)
    post_list = pagination.items
    return render_template('admin/article.html',
                           post_list=post_list,
                           pagination=pagination)


# 添加文章视图
@bp.route('/article/add', methods=['GET', 'POST'])
@login_required
def article_add():
    # 增加文章
    form = PostForm()
    # 获取分类数据
    form.category_id.choices = [(v.id, v.name) for v in Category.query.all()]
    # 获取tag数据
    form.tags.choices = [(v.id, v.name) for v in Tag.query.all()]

    if form.validate_on_submit():
        # 一对多
        post = Post(
            title=form.title.data,
            desc=form.desc.data,
            has_type=form.has_type.data,
            category_id=int(form.category_id.data),
            # content=form.content.data,
            content=markdown.markdown(
                form.content.data,
                extensions=[
                    # toc 自动生成目录
                    'markdown.extensions.toc',
                    # fenced_code 格式化代码
                    'markdown.extensions.fenced_code',
                    # tables 解析表格
                    'markdown.extensions.tables',
                    # extra 含很多拓展
                    'markdown.extensions.extra',
                    # codehilite 语法高亮
                    'markdown.extensions.codehilite',
                ],
                safe_mode=True,
                enable_attributes=False))
        #  多对多
        post.tags = [Tag.query.get(tag_id) for tag_id in form.tags.data]
        db.session.add(post)
        db.session.commit()
        flash(f'{form.title.data}文章添加成功')
        return redirect(url_for('admin.article'))

    return render_template('admin/article_form.html', form=form)


@bp.route('/article/edit/<int:post_id>', methods=['GET', 'POST'])
@login_required
def article_edit(post_id):
    # 修改文章 回显数据
    post = Post.query.get(post_id)
    tags = [tag.id for tag in post.tags]
    form = PostForm(title=post.title,
                    desc=post.desc,
                    category_id=post.category.id,
                    has_type=post.has_type.value,
                    content=post.content,
                    tags=tags)

    form.category_id.choices = [(v.id, v.name) for v in Category.query.all()]
    form.tags.choices = [(v.id, v.name) for v in Tag.query.all()]

    if form.validate_on_submit():
        # 这里才是修改文章的逻辑
        post.title = form.title.data
        post.desc = form.desc.data
        post.has_type = form.has_type.data
        post.category_id = int(form.category_id.data)
        # post.content = form.content.data
        post.content = markdown.markdown(form.content.data,
                                         extensions=[
                                             'markdown.extensions.toc',
                                             'markdown.extensions.fenced_code',
                                             'markdown.extensions.tables',
                                             'markdown.extensions.extra',
                                             'markdown.extensions.codehilite',
                                         ],
                                         safe_mode=True,
                                         enable_attributes=False)
        post.tags = [Tag.query.get(tag_id)
                     for tag_id in form.tags.data]  # 一对多保存
        db.session.add(post)
        db.session.commit()
        flash(f'{form.title.data}文章修改成功')
        return redirect(url_for('admin.article'))
    # 渲染表单
    return render_template('admin/article_form.html', form=form)


@bp.route('/article/delete/<int:post_id>', methods=['GET', 'POST'])
@login_required
def article_del(post_id):
    # 删除文章
    post = Post.query.get(post_id)
    if post:
        db.session.delete(post)
        db.session.commit()
        flash(f'{post.title}文章删除成功')
        return redirect(url_for('admin.article'))


""" 标签管理视图
tag:      查看标签列表
tag.add:  添加标签
tag.edit: 编辑标签
tag.del:  删除标签
"""


@bp.route('/tag')
@login_required
def tag():
    # 查看标签列表
    page = request.args.get('page', 1, type=int)
    pagination = Tag.query.order_by(-Tag.add_date).paginate(page,
                                                            per_page=15,
                                                            error_out=False)
    tag_list = pagination.items
    return render_template('admin/tag.html',
                           tag_list=tag_list,
                           pagination=pagination)


@bp.route('/tag/add', methods=['GET', 'POST'])
@login_required
def tag_add():
    # 增加标签, 实例化标签类
    form = TagForm()
    if form.validate_on_submit():
        # 赋值 从表单获取tag数据
        tag = Tag(name=form.name.data)
        db.session.add(tag)
        db.session.commit()
        flash(f'{form.name.data}添加成功')
        return redirect(url_for('admin.tag'))
    # GET请求进入时展示的渲染页面
    return render_template('admin/tag_form.html', form=form)


@bp.route('/tag/edit/<int:tag_id>', methods=['GET', 'POST'])
@login_required
def tag_edit(tag_id):
    # 修改标签 通过主键获取tag信息
    tag = Tag.query.get(tag_id)
    form = TagForm(name=tag.name)
    if form.validate_on_submit():
        tag.name = form.name.data
        db.session.add(tag)
        db.session.commit()
        flash(f'{form.name.data}修改成功')
        return redirect(url_for('admin.tag'))
    return render_template('admin/tag_form.html', form=form)


@bp.route('/tag/del/<int:tag_id>', methods=['GET', 'POST'])
@login_required
def tag_del(tag_id):
    # 删除标签
    tag = Tag.query.get(tag_id)
    if tag:
        db.session.delete(tag)
        db.session.commit()
        flash(f'{tag.name}删除成功')
        return redirect(url_for('admin.tag'))


""" 用户管理视图
user:      查看用户列表
user.add:  添加用户
user.edit: 编辑用户
user.del:  删除用户
"""


@bp.route('/user')
@login_required
def user():
    # 查看用户列表
    page = request.args.get('page', 1, type=int)
    pagination = User.query.order_by(-User.add_date).paginate(page,
                                                              per_page=10,
                                                              error_out=False)
    user_list = pagination.items
    return render_template('admin/user.html',
                           user_list=user_list,
                           pagination=pagination)


# 添加修改前要先创建模型相关的表单
@bp.route('/user/add', methods=['GET', 'POST'])
@login_required
def user_add():
    form = CreateUserForm()

    # 先获取用户输入数据，验证前端传过来的数据的有效性
    if form.validate_on_submit():
        # 头像处理逻辑 需在表单提交后
        # 放在最外层则走GET请求，一开始就执行了
        from .utils import upload_file_path
        f = form.avatar.data
        avatar_path, filename = upload_file_path('avatar', f)

app/blog/__init__.py
from .import views

app/blog/views.py
from flask import Blueprint, render_template, request
from .models import Post, Category, Tag

# 蓝图实例化
bp = Blueprint(
    'blog',
    __name__,
    url_prefix='/blog',
    static_folder='static',  # 定义静态文件夹
    template_folder='templates')  # 定义模板文件夹
'''
用蓝图来绑定route，把URL定义在该应用当中
@bp.route('/')读取的地址是./blog，而不是/
'''

# @bp.route('/')
# def hello_world():
# return 'Hello world'


# 首页视图
# 在 RealProject/__init__.py 引入url后，index()指向127.0.0.1:8000
def index():
    # 获取文章数据
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(-Post.add_date).paginate(page,
                                                              per_page=15,
                                                              error_out=False)
    post_list = pagination.items
    # 文章预览图 随机获取网上图片
    import random
    imgs = [
        'blog/static/img/poster_01.jpg', 'blog/static/img/poster_02.jpg',
        'blog/static/img/poster_03.jpg', 'blog/static/img/poster_04.jpg',
        'blog/static/img/poster_05.jpg', 'blog/static/img/poster_06.jpg',
        'blog/static/img/poster_07.jpg', 'blog/static/img/poster_08.jpg',
        'blog/static/img/poster_09.jpg', 'blog/static/img/poster_10.jpg',
        'blog/static/img/poster_11.jpg', 'blog/static/img/poster_12.jpg',
        'blog/static/img/poster_13.jpg', 'blog/static/img/poster_14.jpg',
        'blog/static/img/poster_15.jpg', 'blog/static/img/poster_16.jpg'
    ]

    for post in post_list:
        post.img = random.sample(imgs, 1)[0]
        # post.img = random.choice(imgs)

    # posts = [1, 2, 3, 4, 5, 6]  # 模板首页显示6篇文章简介
    return render_template('index.html',
                           posts=post_list,
                           pagination=pagination)  # render_template函数用于读取模板文件


# 分类文章列表视图
@bp.route('/category/<int:cate_id>')
def cates(cate_id):
    cate = Category.query.get(cate_id)
    page = request.args.get('page', default=1, type=int)

    pagination = Post.query.filter(Post.category_id == cate_id).paginate(
        page, per_page=10, error_out=False)

    post_list = pagination.items

    return render_template('cate_list.html',
                           cate=cate,
                           cate_id=cate_id,
                           post_list=post_list,
                           pagination=pagination)


# 文章详情视图
@bp.route('/category/<int:cate_id>/<int:post_id>')
def detail(cate_id, post_id):
    cate = Category.query.get(cate_id)
    post = Post.query.get_or_404(post_id)

    # 上一篇 or 下一篇
    #  1)ID：读取当前ID相邻的上一个或下一个ID
    #  2)发布时间：读取当前文章相邻的之前或之后的发布时间
    prev_post = Post.query.filter(Post.id < post_id).order_by(-Post.id).first()
    next_post = Post.query.filter(Post.id > post_id).order_by(Post.id).first()

    return render_template('detail.html',
                           cate=cate,
                           post=post,
                           prev_post=prev_post,
                           next_post=next_post)


# 侧边栏
@bp.context_processor
def inject_archive():
    # 文章归档日期注入上下文
    posts = Post.query.order_by(-Post.add_date)
    dates = set([post.add_date.strftime("%Y年%m月") for post in posts])

    # 标签
    tags = Tag.query.all()
    for tag in tags:
        tag.style = [
            'is-success', 'is-danger', 'is-black', 'is-light', 'is-primary',
            'is-link', 'is-info', 'is-warning'
        ]

    # 最新文章
    new_posts = posts.limit(6)
    return dict(dates=dates, tags=tags, new_posts=new_posts)


# 文章归档详情视图
@bp.route('/category/<string:date>')
def archive(date):
    # 归档页
    import re
    # 正则匹配年月
    regex = re.compile(r'\d{4}|\d{2}')
    dates = regex.findall(date)

    from sqlalchemy import extract, and_, or_
    page = request.args.get('page', 1, type=int)
    # 根据年月获取数据
    archive_posts = Post.query.filter(
        and_(
            extract('year', Post.add_date) == int(dates[0]),
            extract('month', Post.add_date) == int(dates[1])))
    # 对数据进行分页
    pagination = archive_posts.paginate(page, per_page=15, error_out=False)
    return render_template('archive.html',
                           post_list=pagination.items,
                           pagination=pagination,
                           date=date)


# 标签详情视图
@bp.route('/tags/<int:tag_id>')
def tags(tag_id):
    # 标签页
    tag = Tag.query.get(tag_id)
    return render_template('tags.html', post_list=tag.post, tag=tag)


# 搜索视图
@bp.route('/search')
def search():
    # 获取表单输入的数据
    words = request.args.get("words")
    page = request.args.get('page', 1, type=int)
    # filter 查询出多条数据 title 搜索结果只匹配标题
    pagination = Post.query.filter(
        Post.title.like("%" + words + "%")).paginate(page,
                                                     per_page=10,
                                                     error_out=False)
    post_list = pagination.items

    return render_template('search.html',
                           words=words,
                           post_list=post_list,
                           pagination=pagination)

app/blog/templates/base.html
<!DOCTYPE html>
<html lang="cn">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}摸鱼歌的博客{% endblock title %}</title>
    <link
      rel="icon"
      href="{{ url_for('blog.static', filename='img/icon.png') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('blog.static', filename='css/buefy.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('blog.static', filename='css/materialdesignicons.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('blog.static', filename='css/style.css') }}"
    />
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@6.x/css/materialdesignicons.min.css">-->

    {% block extra_head_style %}{% endblock extra_head_style %}
  </head>

  <body>
    <div id="app" style="height: 100%">
        <header>
            <!-- 导航 -->
          {% block navbar %}
          <template>
            <b-navbar spaced shadow>
              <template #brand>
                <b-navbar-item href="/">
                  <img
                    src="{{ url_for('blog.static', filename='img/logo1.png') }}"
                    alt="FlaskBlog"
                  />
                </b-navbar-item>
              </template>
              <template #start>
                <b-navbar-item href="/"> 首页 </b-navbar-item>
                {% for cate in categorys %}
                <b-navbar-item 
                {% if cate.id==cate_id %} class="is-active"{% endif %}  href="{{ url_for('blog.cates', cate_id=cate.id) }}" >
                  {{ cate.name }}
                  </b-navbar-item>
                {% endfor %}
              </template>

              <template #end>
                <b-navbar-item tag="div">
                  <!-- 判断用户是否已登录 -->
                  {% if g.user %}
                  <figure class="image">
                    <img
                      class="is-rounded"
                      src="/admin/static/{{ g.user.avatar }}"
                      alt="{{ g.user.username }}"
                    />
                  </figure>
                  <div class="buttons">
                    <!-- 获取用户信息 -->
                    <a class="button is-link"
                      >欢迎您 {{ g.user['username'] }}</a
                    >
                    {% if g.user.is_super_user %}
                    <a class="button is-success" href="{{ url_for('admin.index') }}">管理后台</a>
                    {% else %}
                    <a class="button is-success" href="{{ url_for('auth.userinfo') }}">个人中心</a>
                    {% endif %}
                    <!-- 显示退出按钮 -->
                    <a
                      class="button is-danger"
                      href="{{ url_for('auth.logout') }}"
                      >退出</a
                    >
                  </div>
                  {% else %}
                  <!-- 用户未登录，显示登录注册按钮 -->
                  <div class="buttons">
                    <a
                      class="button is-primary"
                      href="{{ url_for('auth.register') }}"
                    >
                      <strong>注册</strong>
                    </a>
                    <a
                      class="button is-light"
                      href="{{ url_for('auth.login') }}"
                      >登录</a
                    >
                  </div>
                  {% endif %}
                </b-navbar-item>
              </template>
            </b-navbar>
          </template>
          {% endblock navbar %}
          <!-- 导航 end -->

        </header>
      <div class="container is-fluid1" style="height: 100%">
        <div class="is-block" style="height: 100%">
          {% block hero %}
          <!--<section class="hero is-medium is-primary">
            <div class="hero-body">
              <p class="title">Large hero</p>
              <p class="subtitle">Large subtitle</p>
            </div>
          </section>-->
          <section class="banner">
            <div class="carousel-item">
                <img class="carousel-img" src="../blog/static/image/1.jpg" alt="">
                <img class="carousel-img" src="../blog/static/image/2.jpg" alt="">
                <img class="carousel-img" src="../blog/static/image/3.jpg" alt="">
                <img class="carousel-img" src="../blog/static/image/4.jpg" alt="">
            </div>
            <div class="carousel-page">
                <span href="#" class="carousel-has"></span>
                <span href="#" class="carousel-has"></span>
                <span href="#" class="carousel-has"></span>
                <span href="#" class="carousel-has"></span>
            </div>
          </section>
          {% endblock hero %}

          <!-- note: -->
          {% block main %}
          <div class="box is-marginless is-shadowless is-radiusless">
            {% block box %}
            <div class="columns is-multiline">
              <!-- 2022-9-17 目前没有数据，可以暂时传一假数据过来 -->
              {% for post in posts %}
              <div class="column is-4-fullhd">
                <div class="card">
                  <div class="card-image">
                    <figure class="image is-4by3">
                      <img src="{{ post.img }}" width="100%" />
                    </figure>
                  </div>
                  <div class="card-content">
                    <div class="media">
                      <div class="media-content">
                        <p class="title is-4">
                          <a
                            href="{{ url_for('blog.detail', cate_id=post.category.id, post_id=post.id) }}"
                          >
                            {{ post.title }}
                          </a>
                        </p>
                      </div>
                    </div>

                    <div class="content word-info">
                      <p class="has-text-grey is-size-8">{{ post.desc }}</p>
                      <time datetime="{{ post.add_date }}" class="is-size-8">
                        {{ post.add_date }}
                      </time>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>

            <nav
              class="pagination is-small"
              role="navigation"
              aria-label="pagination"
            >
              {% if pagination.has_prev %}
              <a
                href="{{ url_for('index') }}?page={{ pagination.prev_num }}"
                class="pagination-previous"
                title="This is the first page"
                >上一页</a
              >
              {% endif %} {% if pagination.has_next %}
              <a
                href="{{ url_for('index') }}?page={{ pagination.next_num }}"
                class="pagination-next"
                >下一页</a
              >
              {% endif %}

              <ul class="pagination-list">
                {% for page in pagination.iter_pages() %} {% if page %} {% if
                page != pagination.page %}
                <li>
                  <a
                    href="{{ url_for('index') }}?page={{ page }}"
                    class="pagination-link"
                    aria-label="Page 1"
                    aria-current="page"
                    >{{ page }}</a
                  >
                </li>
                {% else %}
                <li>
                  <a
                    class="pagination-link is-current"
                    aria-label="Page 1"
                    aria-current="page"
                    >{{ page }}</a
                  >
                </li>
                {% endif %} {% else %}
                <span class="pagination-ellipsis">&hellip;</span>
                {% endif %} {% endfor %}
              </ul>
            </nav>
            {% endblock box %}
          </div>
          {% endblock main %} {% block footer %}
          <div class="footer has-background-black-ter">
            <div class="has-text-centered has-text-grey-light">
              © 2022
              <a
                class="has-text-grey-light"
                href="https://gitee.com/aimoyu/"
                target="_blank"
                >爱摸鱼</a
              >
              版权所有 备案号：沪ICP备20221234号
            </div>
          </div>
          {% endblock footer %}
        </div>
      </div>
    </div>

    <script src="{{ url_for('blog.static', filename='js/vue.js') }}"></script>
    <script src="{{ url_for('blog.static', filename='js/buefy.min.js') }}"></script>
    {% block extra_foot_script %}{% endblock extra_foot_script %}
    <script>
      var app = new Vue({
        el: "#app",
        data: {},
        methods: {},
      });
    </script>
    {% block vue_script %}
    {% endblock vue_script %}

  </body>
</html>

app/blog/templates/cate_list.html
{% extends 'base.html' %} {% block title %}{{ cate.name }}{% endblock title %}
{% block hero %}{% endblock hero %} {% block box %}
<div class="columns">
  <div class="column is-9">
    <div class="box is-shadowless has-background-light">
      {% block breadcrumb %}
      <!-- 路径导航 -->
      <nav class="breadcrumb is-small" aria-label="breadcrumbs">
        <ul>
          <li><a href="/">首页</a></li>
          <li class="is-active">
            <a href="#" aria-current="page">{{ cate.name }}</a>
          </li>
        </ul>
      </nav>
      {% endblock breadcrumb %}
    </div>

    {% block cate_box %} {% for post in post_list %}
    <div class="pl-2">
      <h1 class="is-size-4">
        <a
          href="{{ url_for('blog.detail', cate_id=post.category.id, post_id=post.id) }}"
          >{{ post.title }}</a
        >
      </h1>
      <p class="has-text-grey-light is-size-6 mt-1">
        <span class="icon"
          ><i class="mdi mdi-clipboard-text-clock-outline"></i></span
        >{{ post.add_date }}
        <span class="icon" ><i class="mdi mdi-shape-outline"></i></span>{{
        post.category.name }}
        <span class="icon"><i class="mdi mdi-tag-heart-outline"></i></span>{{
        post.tags|join(',') }}
      </p>
      <div class="has-text-grey mt-1">{{ post.desc }}</div>
    </div>
    <div class="dropdown-divider mb-3"></div>
    {% endfor %} {% block pagination %}
    <nav class="pagination is-small" role="navigation" aria-label="pagination">
      {% if pagination.has_prev %}
      <a
        href="{{ url_for('blog.cates', cate_id=cate.id ) }}?page={{ pagination.prev_num }}"
        class="pagination-previous"
        title="This is the first page"
        >上一页</a
      >
      {% endif %} {% if pagination.has_next %}
      <a
        href="{{ url_for('blog.cates', cate_id=cate.id) }}?page={{ pagination.next_num }}"
        class="pagination-next"
        >下一页</a
      >
      {% endif %}

      <ul class="pagination-list">
        {% for page in pagination.iter_pages() %} {% if page %} {% if page !=
        pagination.page %}
        <li>
          <a
            href="{{ url_for('blog.cates', cate_id=cate.id) }}?page={{ page }}"
            class="pagination-link"
            aria-label="Page 1"
            aria-current="page"
            >{{ page }}</a
          >
        </li>
        {% else %}
        <li>
          <a
            class="pagination-link is-current"
            aria-label="Page 1"
            aria-current="page"
            >{{ page }}</a
          >
        </li>
        {% endif %} {% else %}
        <span class="pagination-ellipsis">&hellip;</span>
        {% endif %} {% endfor %}
      </ul>
    </nav>
    {% endblock pagination %} {% endblock cate_box %}
  </div>
  <div class="column">
    <div class="box is-shadowless is-aside">
      <h1 class="is-size-6 icon-text">
        <span class="icon"><i class="mdi mdi-calendar-month-outline"></i></span>
        最新文章
      </h1>
      <div class="dropdown-divider"></div>
      <ul>
        {% for post in new_posts %}
        <li class="pl-2">
          <span class="has-text-grey-light">{{ loop.index }}.</span>
          <a
            href="{{ url_for('blog.detail', cate_id=post.category.id, post_id=post.id) }}"
            >{{ post.title }}</a
          >
        </li>
        <div class="dropdown-divider"></div>
        {% endfor %}
      </ul>
    </div>

    <div class="box is-shadowless is-aside">
      <h1 class="is-size-6 icon-text">
        <span class="icon"><i class="mdi mdi-calendar-month-outline"></i></span>
        归档
      </h1>
      <div class="dropdown-divider"></div>
      <ul>
        {% for date in dates %}
        <li class="pl-2">
          <a href="{{ url_for('blog.archive', date=date) }}">{{ date }}</a>
        </li>
        <div class="dropdown-divider"></div>
        {% endfor %}
      </ul>
    </div>

    <div class="box is-shadowless is-aside">
      <h1 class="is-size-6 icon-text">
        <span class="icon"><i class="mdi mdi-search-web"></i></span>
        搜索
      </h1>
      <div class="dropdown-divider"></div>
      <form action="{{ url_for('blog.search') }}" method="get">
        <div class="field has-addons">
          <div class="control">
            <input
              class="input"
              type="search"
              value="{{ words }}"
              name="words"
              placeholder="请输入关键字"
            />
          </div>
          <div class="control">
            <input type="submit" value="Search" class="button is-info" />
          </div>
        </div>
      </form>
    </div>

    <div class="box is-shadowless is-aside">
      <h1 class="is-size-6 icon-text">
        <span class="icon"><i class="mdi mdi-tag-multiple-outline"></i></span>
        标签
      </h1>
      <div class="dropdown-divider"></div>

      <div class="tags">
        {% for tag in tags %}
        <a
          class="tag {{ tag.style|random() }}"
          href="{{ url_for('blog.tags', tag_id=tag.id) }}"
          >{{ tag.name }}</a
        >
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock box %}

app/blog/templates/index.html
{% extends 'base.html' %}

app/blog/templates/tags.html
{% extends 'cate_list.html' %} {% block title %}{{ tag }} {% endblock title %}
{% block hero %}{% endblock hero %} {% block breadcrumb %}
<nav class="breadcrumb is-small" aria-label="breadcrumbs">
  <ul>
    <li><a href="/">首页</a></li>
    <li class="is-active"><a href="#" aria-current="page">{{ tag }}</a></li>
  </ul>
</nav>
{% endblock breadcrumb %} {% block pagination %} {% endblock pagination %}